name: PMD Check using Gradle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: gradle --build-file=build.gradle.1
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run PMD
        run: |
          gradle --build-file=build.gradle.1 pmdMain

      - name: Upload PMD report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: build/reports/pmd 
